In [2]:
import torch
# tensor : fundamental building block in machine learning
torch.__version__

'1.13.0+cpu'

In [2]:
scalar = torch.tensor(7)
# scalar : single no. zero-dimensional tensor
scalar

tensor(7)

In [3]:
scalar.ndim
# ndim : no. of diension of given var ex: scalar -> dimension(0)

0

In [4]:
scalar.item() 
# it used to retrieve no from tensor

7

In [5]:
# vector: single dimension
vector = torch.tensor([7,9])
vector

tensor([7, 9])

In [6]:
vector.shape
# size of vector

torch.Size([2])

In [7]:
vector.ndim

1

In [14]:
# Matrix
MATRIX = torch.tensor([[7, 1,8], 
                       [9, 6,5]])
MATRIX

tensor([[7, 1, 8],
        [9, 6, 5]])

In [15]:
MATRIX.ndim

2

In [16]:
MATRIX.shape

torch.Size([2, 3])

In [5]:
# Tensor
TENSOR = torch.tensor([[[1,3,4,5],[4,5,6,7],[3,1,26,1],[2,3,45,7]]])
TENSOR

tensor([[[ 1,  3,  4,  5],
         [ 4,  5,  6,  7],
         [ 3,  1, 26,  1],
         [ 2,  3, 45,  7]]])

In [6]:
TENSOR.ndim

3

In [7]:
TENSOR.shape

torch.Size([1, 4, 4])